### ISSUE TITLE
Feedback: UI Enhancements

### ISSUE THREAD

**Issue by asadpiz** [maciejmatu/mosaic#2]
First of all, thanks for creating this. We're having a lot of fun with it during the quarantine. Having played it a few times, I have some suggestions for the UI improvements. As it's not a source code issue, I can't do much about it.
1. **Blue and Green tiles are hard to distinguish**. It would be great if one of these tiles has a darker color.
 
![image](https://user-images.githubusercontent.com/3435875/81865778-995a6200-956e-11ea-9b4d-0e733db57f97.png)

2. It's also hard to see the disabled tiles on the board. It would be great if these are not covered with white shadow or have plain colors.

![image](https://user-images.githubusercontent.com/3435875/81865964-d32b6880-956e-11ea-9ce1-f1b8922439d2.png)

**Comment by maciejmatu** [comment]
Glad you enjoy it! Thanks for the feedback, I will implement some fixes for it during the weekend if I get a chance. I'm not sure how I'll fix those, but I'll consult a friend who designed it, maybe he'll have some ideas

Also, I'm really happy people play it and it brings some joy 😄
